services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=urlShortening